import uuid
from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='Case',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('title',models.CharField(max_length=200)),('slug',models.SlugField(max_length=220,unique=True)),('domain',models.CharField(max_length=100)),('difficulty',models.CharField(choices=[('beginner','Beginner'),('intermediate','Intermediate'),('advanced','Advanced'),('expert','Expert')],default='intermediate',max_length=20)),('overview',models.TextField()),('objective',models.TextField()),('rules',models.JSONField(blank=True,default=list)),('time_limit_seconds',models.PositiveIntegerField(blank=True,null=True)),('is_published',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='authored_cases',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='CaseEntity',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=200)),('entity_type',models.CharField(choices=[('person','Person'),('organization','Organization'),('location','Location'),('event','Event'),('object','Object'),('other','Other')],max_length=30)),('description',models.TextField(blank=True)),('is_hidden',models.BooleanField(default=False)),('case',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='entities',to='cases.case'))]),
        migrations.CreateModel(name='Evidence',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('title',models.CharField(max_length=200)),('evidence_type',models.CharField(choices=[('document','Document'),('report','Report'),('statement','Statement'),('image','Image'),('message','Message'),('timeline','Timeline'),('financial_record','Financial Record'),('log','Log'),('chart','Chart'),('other','Other')],max_length=30)),('content',models.TextField()),('visibility',models.CharField(choices=[('initial','Initial'),('discoverable','Discoverable'),('conditional','Conditional'),('hidden','Hidden')],default='initial',max_length=20)),('reliability',models.DecimalField(decimal_places=4,default=.5,max_digits=5)),('relevance',models.DecimalField(decimal_places=4,default=.5,max_digits=5)),('directness',models.DecimalField(decimal_places=4,default=.5,max_digits=5)),('is_red_herring',models.BooleanField(default=False)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('case',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='evidence',to='cases.case'))]),
        migrations.CreateModel(name='CaseHypothesis',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('code',models.CharField(max_length=40)),('statement',models.TextField()),('kind',models.CharField(choices=[('required','Required'),('accepted','Accepted'),('rejected','Rejected'),('partial','Partial')],max_length=20)),('minimum_evidence',models.PositiveIntegerField(default=1)),('explanation',models.TextField(blank=True)),('case',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='solution_hypotheses',to='cases.case')),('required_evidence',models.ManyToManyField(blank=True,related_name='required_for_hypotheses',to='cases.evidence'))]),
        migrations.CreateModel(name='EvidenceRelation',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('relation',models.CharField(choices=[('supports','Supports'),('contradicts','Contradicts'),('corroborates','Corroborates'),('references','References')],max_length=30)),('notes',models.TextField(blank=True)),('source',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='outgoing_relations',to='cases.evidence')),('target',models.ForeignKey(on_delete=django.db.models.CASCADE,related_name='incoming_relations',to='cases.evidence'))]),
        migrations.CreateModel(name='EntityRelationship',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('relation',models.CharField(max_length=80)),('description',models.TextField(blank=True)),('is_hidden',models.BooleanField(default=False)),('case',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='relationships',to='cases.case')),('source',models.ForeignKey(on_delete=django.db.models.CASCADE,related_name='outgoing_relationships',to='cases.caseentity')),('target',models.ForeignKey(on_delete=django.db.models.CASCADE,related_name='incoming_relationships',to='cases.caseentity'))]),
        migrations.CreateModel(name='EvidenceUnlockRule',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('rule_type',models.CharField(choices=[('evidence_access','Evidence access'),('keyword','Keyword'),('hypothesis','Hypothesis'),('event_count','Event count')],max_length=40)),('config',models.JSONField(default=dict)),('description',models.TextField(blank=True)),('case',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='unlock_rules',to='cases.case')),('target_evidence',models.OneToOneField(on_delete=django.db.models.CASCADE,related_name='unlock_rule',to='cases.evidence'))]),
        migrations.CreateModel(name='CaseSkillWeight',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('skill_key',models.SlugField(max_length=80)),('weight',models.DecimalField(decimal_places=4,max_digits=6)),('case',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='skill_weights',to='cases.case'))]),
        migrations.CreateModel(name='AdaptiveCasePolicy',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('enabled',models.BooleanField(default=False)),('rules',models.JSONField(blank=True,default=list)),('preserve_truth',models.BooleanField(default=True)),('case',models.OneToOneField(on_delete=django.db.models.CASCADE,related_name='adaptive_policy',to='cases.case'))]),
        migrations.AddConstraint(model_name='caseentity',constraint=models.UniqueConstraint(fields=('case','name'),name='uniq_case_entity_name')),migrations.AddConstraint(model_name='evidencerelation',constraint=models.UniqueConstraint(fields=('source','target','relation'),name='uniq_evidence_relation')),migrations.AddConstraint(model_name='casehypothesis',constraint=models.UniqueConstraint(fields=('case','code'),name='uniq_case_hypothesis_code')),migrations.AddConstraint(model_name='caseskillweight',constraint=models.UniqueConstraint(fields=('case','skill_key'),name='uniq_case_skill_weight')),migrations.AddIndex(model_name='evidence',index=models.Index(fields=['case','visibility'],name='cases_evide_case_id_5f4f54_idx'))]
