import uuid
from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),('cases','0001_initial')]
    operations=[
        migrations.CreateModel(name='InvestigationSession',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('status',models.CharField(choices=[('active','Active'),('paused','Paused'),('submitted','Submitted'),('evaluated','Evaluated'),('abandoned','Abandoned')],default='active',max_length=20)),('started_at',models.DateTimeField(auto_now_add=True)),('last_activity_at',models.DateTimeField(auto_now=True)),('submitted_at',models.DateTimeField(blank=True,null=True)),('state',models.JSONField(blank=True,default=dict)),('final_answer',models.TextField(blank=True)),('case',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='sessions',to='cases.case')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='investigation_sessions',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='EvidenceAccess',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('first_accessed_at',models.DateTimeField(auto_now_add=True)),('last_accessed_at',models.DateTimeField(auto_now=True)),('access_count',models.PositiveIntegerField(default=1)),('seconds_spent',models.PositiveIntegerField(default=0)),('evidence',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='session_accesses',to='cases.evidence')),('session',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='evidence_accesses',to='investigations.investigationsession'))]),
        migrations.CreateModel(name='Hypothesis',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('statement',models.TextField()),('confidence',models.DecimalField(decimal_places=4,default=.5,max_digits=5)),('status',models.CharField(choices=[('unverified','Unverified'),('supported','Supported'),('refuted','Refuted'),('abandoned','Abandoned')],default='unverified',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('session',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='hypotheses',to='investigations.investigationsession')),('evidence',models.ManyToManyField(blank=True,related_name='user_hypotheses',to='cases.evidence'))]),
        migrations.CreateModel(name='InvestigationNote',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('title',models.CharField(blank=True,max_length=200)),('content',models.TextField()),('tags',models.JSONField(blank=True,default=list)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('session',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='notes',to='investigations.investigationsession'))]),
        migrations.CreateModel(name='InvestigationEvent',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('event_type',models.CharField(max_length=60)),('occurred_at',models.DateTimeField(auto_now_add=True)),('payload',models.JSONField(blank=True,default=dict)),('sequence_number',models.PositiveIntegerField()),('session',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='events',to='investigations.investigationsession'))]),
        migrations.AddConstraint(model_name='evidenceaccess',constraint=models.UniqueConstraint(fields=('session','evidence'),name='uniq_session_evidence_access')),migrations.AddConstraint(model_name='investigationevent',constraint=models.UniqueConstraint(fields=('session','sequence_number'),name='uniq_event_sequence'))]
