from django.core.management.base import BaseCommand,CommandError
from django.contrib.auth import get_user_model
from apps.cases.models import Case,CaseEntity,EntityRelationship,Evidence,EvidenceRelation,CaseHypothesis,EvidenceUnlockRule,CaseSkillWeight
class Command(BaseCommand):
    help='Create a deterministic demo investigation case.'
    def handle(self,*args,**kwargs):
        User=get_user_model(); admin=User.objects.filter(is_superuser=True).first()
        if not admin: raise CommandError('Create a Django superuser before running seed_demo.')
        case,_=Case.objects.get_or_create(slug='the-missing-research-data',defaults={'title':'The Missing Research Data','domain':'Research Integrity','difficulty':'intermediate','overview':'A laboratory dataset disappeared shortly before an external audit. Multiple people had access and several records disagree.','objective':'Determine what happened to the dataset, identify the strongest explanation, and support your conclusion with evidence.','rules':['Do not assume a statement is true merely because it is confident.','You may request evidence through the investigation agent.','Your final conclusion must distinguish facts, inferences and uncertainty.'],'is_published':True,'created_by':admin})
        if case.evidence.exists(): self.stdout.write('Demo case already seeded.'); return
        e1=Evidence.objects.create(case=case,title='Access Log — 18:42',evidence_type='log',content='The laboratory server records a successful export from workstation R-17 at 18:42. The account belonged to Mira Shah.',visibility='initial',reliability=.92,relevance=.95,directness=.85)
        e2=Evidence.objects.create(case=case,title='Mira Statement',evidence_type='statement',content='Mira says she left the lab at 18:10 and did not return. She says her workstation was locked when she left.',visibility='initial',reliability=.62,relevance=.90,directness=.55)
        e3=Evidence.objects.create(case=case,title='Backup Audit',evidence_type='report',content='The backup system shows the missing dataset was copied to an external drive at 18:44. The copy completed successfully.',visibility='initial',reliability=.96,relevance=.94,directness=.90)
        e4=Evidence.objects.create(case=case,title='Door Sensor',evidence_type='log',content='The lab door opened at 18:39 using badge B-22, assigned to Arun Mehta. The door closed at 18:47.',visibility='initial',reliability=.94,relevance=.91,directness=.88)
        e5=Evidence.objects.create(case=case,title='Camera Gap',evidence_type='report',content='The corridor camera has a seven-minute recording gap from 18:40 to 18:47 caused by a storage fault. This does not establish who used the workstation.',visibility='initial',reliability=.90,relevance=.72,directness=.40,is_red_herring=True)
        e6=Evidence.objects.create(case=case,title='USB Inventory',evidence_type='document',content='An external drive registered to Arun was connected to workstation R-17 at 18:43. Its serial number matches a drive later found in the archive room.',visibility='discoverable',reliability=.97,relevance=.98,directness=.93)
        e7=Evidence.objects.create(case=case,title='Archive Room Note',evidence_type='statement',content='A technician reports seeing Arun in the archive room at 18:50 carrying a black external drive. This observation is consistent with the USB inventory.',visibility='discoverable',reliability=.70,relevance=.86,directness=.65)
        e8=Evidence.objects.create(case=case,title='Mira Credential Review',evidence_type='report',content='The identity system shows Mira authenticated remotely from a different network at 18:41, but this is not proof that she initiated the workstation export.',visibility='conditional',reliability=.88,relevance=.82,directness=.50)
        EvidenceRelation.objects.create(source=e1,target=e6,relation='corroborates'); EvidenceRelation.objects.create(source=e4,target=e6,relation='supports'); EvidenceRelation.objects.create(source=e5,target=e6,relation='references')
        EvidenceUnlockRule.objects.create(case=case,target_evidence=e6,rule_type='evidence_access',config={'evidence_id':str(e4.id)},description='Inspecting the door event unlocks the USB inventory.')
        EvidenceUnlockRule.objects.create(case=case,target_evidence=e7,rule_type='keyword',config={'keywords':['external drive']},description='Investigate the drive before the archive note becomes available.')
        EvidenceUnlockRule.objects.create(case=case,target_evidence=e8,rule_type='hypothesis',config={'contains':'Mira'},description='Form a hypothesis involving Mira to unlock credential context.')
        h=CaseHypothesis.objects.create(case=case,code='H-01',statement='Arun Mehta copied the missing research dataset using the external drive.',kind='required',minimum_evidence=2,explanation='The strongest supported explanation uses the door log, USB inventory and backup audit.')
        h.required_evidence.set([e3,e4,e6]); CaseHypothesis.objects.create(case=case,code='H-02',statement='Mira Shah copied the dataset.',kind='accepted',minimum_evidence=2,explanation='A defensible alternative requires evidence beyond the remote authentication record.')
        CaseSkillWeight.objects.bulk_create([CaseSkillWeight(case=case,skill_key='evidence_evaluation',weight=.16),CaseSkillWeight(case=case,skill_key='attention_to_detail',weight=.14),CaseSkillWeight(case=case,skill_key='hypothesis_testing',weight=.13)])
        self.stdout.write(self.style.SUCCESS(f'Seeded {case.title}'))
